name: 'Release Webhook Notification'
description: 'Sendet Release-Metadaten und Notizen als Webhook nach erfolgreichem Release'
inputs:
  webhook_url:
    description: 'Die Ziel-URL für den Webhook'
    required: true
  package_file:
    description: 'Pfad zur package.yml'
    required: false
    default: 'package.yml'
runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      run: pip install yq

    - name: Extract metadata
      id: meta
      shell: bash
      run: |
        VERSION=$(yq -r '.version' ${{ inputs.package_file }})
        RELEASE_DATE=$(yq -r '.release_datetime // ""' ${{ inputs.package_file }})
        REPO_URL=$(yq -r '.repository_url // "https://github.com/${{ github.repository }}"' ${{ inputs.package_file }})
        ZIP_URL="https://github.com/${{ github.repository }}/archive/${{ github.event.release.tag_name }}.zip"
        NOTES="${{ github.event.release.body }}"
        NOTES_B64=$(echo "$NOTES" | base64 -w0)
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          STATUS="prerelease"
        else
          STATUS="release"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_OUTPUT
        echo "REPO_URL=$REPO_URL" >> $GITHUB_OUTPUT
        echo "ZIP_URL=$ZIP_URL" >> $GITHUB_OUTPUT
        echo "NOTES_B64=$NOTES_B64" >> $GITHUB_OUTPUT
        echo "STATUS=$STATUS" >> $GITHUB_OUTPUT
