runs:
  using: "composite"
  steps:
    - name: Set release metadata
      shell: bash
      run: |
        set -e
        pip install yq
        if [ ! -f "${{ inputs.package_file }}" ]; then
          echo "File not found: ${{ inputs.package_file }}"
          exit 1
        fi
        DATE="$(date -u +'%Y-%m-%d %H:%M:%S')"
        REPO_URL="https://github.com/${{ github.repository }}"
        PRERELEASE="false"
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          PRERELEASE="true"
        fi
        yq -y \
          '.release_datetime = strenv(DATE) | .repository_url = strenv(REPO_URL) | .prerelease = strenv(PRERELEASE)' \
          -i ${{ inputs.package_file }}
    - name: Commit changes
      shell: bash
      run: |
        set -e
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.package_file }}
        git commit -m "chore: set release datetime, repo URL and prerelease status in package.yml" || echo "No changes to commit"
        git push
