name: 'Pre-Release Updater'
description: 'Setzt Release-Datum, Repo-URL und Pre-Release-Status in package.yml'
inputs:
  package_file:
    description: 'Pfad zur package.yml'
    required: false
    default: 'package.yml'
runs:
  using: "composite"
  steps:
    - name: Set release metadata
      shell: bash
      run: |
        pip install yq
        DATE="$(date -u +'%Y-%m-%d %H:%M:%S')"
        REPO_URL="https://github.com/${{ github.repository }}"
        # Default: false
        PRERELEASE="false"
        # Wenn das Release-Event existiert und prerelease true ist, dann true
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          PRERELEASE="true"
        fi
        yq -y \
          '.release_datetime = strenv(DATE) | .repository_url = strenv(REPO_URL) | .prerelease = strenv(PRERELEASE)' \
          -i ${{ inputs.package_file }}
    - name: Commit changes
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.package_file }}
        git commit -m "chore: set release datetime, repo URL and prerelease status in package.yml"
        git push
